### ISSUE TITLE
centos 报错，mac平台没问题

### ISSUE THREAD

**Issue by gexiaowei** [oott123/node-pandan#1]
centos 报错，mac平台没问题
module.js:472
    throw err;
    ^

Error: Cannot find module './lib/roomapi'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/lab/barrage/node_modules/pandan/index.js:6:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/lab/barrage/lib/panda.js:7:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by oott123** [comment]
fixed, thx

**Comment by gexiaowei** [comment]
请发布下npm

**Comment by oott123** [comment]
published at 0.0.3, thx
